### ISSUE TITLE
BDS Lock File

### ISSUE THREAD

**Issue by jnordling** [knu2xs/arcgis-business-analyst-spatial-overlay-multithreaded#1]
When I use this with 1 process, it runs fine. When I run with multi code I get Lock errors for the BDS file. I think im missing something. Any ideas?

**Comment by jnordling** [comment]
So I finally figured out the issue (thanks to ESRI Support!!!) I will add a small PR which will make this work with BDS files.

**Comment by knu2xs** [comment]
Resolved by jnording
